version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.9.1
  aws-ecs: circleci/aws-ecs@1.2.0
jobs:
  test:
    docker:
      - image: python:3.7
        environment:
          FLASK_ENV: test
    working_directory: ~/app
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m pytest -v tests/test_script.py
      - store_test_results:
          path: _build/test/lib/flask_app
workflows:
  version: 2
  test-and-build:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          repo: "flask-app"
          tag: "${CIRCLE_BRANCH}_${CIRCLE_SHA1},${CIRCLE_BRANCH}_latest"
          requires:
            - test
          filters:
            branches:
              only:
                - main
